export const categoriesInfo = [
  {
    id: "Heritage",
    icon: "ri-building-4-line",
    color: "text-orange-500",
    bg: "bg-orange-50",
    border: "border-orange-200",
    gradient: "from-orange-500 to-amber-500",
    title: "Heritage",
    subtitle: "Historical Wonders",
    description: "Explore India's magnificent forts, palaces, UNESCO World Heritage Sites, and ancient monuments that tell the story of thousands of years of history.",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80",
  },
  {
    id: "Nature",
    icon: "ri-landscape-line",
    color: "text-green-600",
    bg: "bg-green-50",
    border: "border-green-200",
    gradient: "from-green-500 to-emerald-500",
    title: "Nature",
    subtitle: "Natural Beauty",
    description: "From the snow-capped Himalayas to the lush backwaters of Kerala — discover India's breathtaking natural landscapes, national parks, and wildlife sanctuaries.",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
  },
  {
    id: "Adventure",
    icon: "ri-treasure-map-line",
    color: "text-purple-600",
    bg: "bg-purple-50",
    border: "border-purple-200",
    gradient: "from-purple-500 to-violet-500",
    title: "Adventure",
    subtitle: "Thrill & Excitement",
    description: "Paragliding in Manali, trekking in Ladakh, river rafting in Rishikesh — India is an adventure lover's paradise with thrilling experiences across every terrain.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
  },
  {
    id: "Religious",
    icon: "ri-bank-line",
    color: "text-pink-500",
    bg: "bg-pink-50",
    border: "border-pink-200",
    gradient: "from-pink-500 to-rose-500",
    title: "Religious",
    subtitle: "Sacred Destinations",
    description: "India is the birthplace of multiple religions. From the ghats of Varanasi to the temples of Tamil Nadu — experience profound spirituality and divine heritage.",
    image: "https://images.unsplash.com/photo-1609139003551-4a7de12b8c72?w=800&q=80",
  },
  {
    id: "Culture",
    icon: "ri-flower-line",
    color: "text-yellow-500",
    bg: "bg-yellow-50",
    border: "border-yellow-200",
    gradient: "from-yellow-500 to-orange-400",
    title: "Culture",
    subtitle: "Traditions & Art",
    description: "India's rich cultural tapestry includes classical dance forms, folk art, festivals, cuisine, and traditions that vary beautifully from state to state.",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80",
  },
]